src/main/java/ais/demo/models/organization/Organization.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ais.demo.models.organization;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Patskevich.S
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Organization {
	
	@JsonIgnore
	private String id;
	private String CompanyName;
	private String UNP;
	private int DistrictCode;
	@JsonIgnore
	private String DistrictCodeName;
	private String District;	
	private String City;

	@JsonIgnore
	public Map getDistrictCodeList()
	{
		Map<Integer, String> list = new HashMap <>();
		
		list.put(0, "");
		list.put(1, "г. Минск");
		list.put(2, "Минская");
		list.put(3, "Брестская");
		list.put(4, "Витебская");
		list.put(5, "Гомельская");
		list.put(6, "Гродненская");
		list.put(7, "Могилевская");
		
		return list;
	}
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	@JsonProperty("CompanyName")
	public String getCompanyName() {
		return CompanyName;
	}

	public void setCompanyName(String CompanyName) {
		this.CompanyName = CompanyName;
	}
	@JsonProperty("UNP")
	public String getUNP() {
		return UNP;
	}

	public void setUNP(String UNP) {
		this.UNP = UNP;
	}
	@JsonProperty("DistrictCode")
	public int getDistrictCode() {
		return DistrictCode;
	}

	public void setDistrictCode(int DistrictCode) {
		this.DistrictCode = DistrictCode;
	}

	public String getDistrictCodeName() {
		return DistrictCodeName;
	}
	@JsonProperty("District")
	public String getDistrict() {
		return District;
	}

	public void setDistrict(String District) {
		this.District = District;
	}
	@JsonProperty("City")
	public String getCity() {
		return City;
	}

	public void setCity(String City) {
		this.City = City;
	}
	
	@SuppressWarnings("unchecked")
    @JsonProperty("_id")
    private void unpackOid(Map<String,Object> id) {
        this.id = (String)id.get("$oid");
    }
	
	@SuppressWarnings("unchecked")
    @JsonProperty("DistrictCode")
    private void unpackDistrictCode(int DistrictCode) {
        this.DistrictCode = DistrictCode;
		this.DistrictCodeName = (String)getDistrictCodeList().get(DistrictCode);
    }
	
	@Override
    public String toString() {
        return "Organization{" +
                "DistrictCode=" + DistrictCode +
				", DistrictCodeName='" + DistrictCodeName + '\'' +
                ", id='" + id + '\'' +
                ", CompanyName='" + CompanyName + '\'' +
                ", UNP='" + UNP +  '\'' +
				", District='" + District + '\'' +
				", City='" + City + '\'' +
                '}';
    }
}

src/main/java/ais/demo/models/organization/OrganizationImpl.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ais.demo.models.organization;

import ais.demo.helpers.ResponseResult;
import ais.demo.helpers.UriHelperNotApi;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author Patskevich.S
 */
@Service
public class OrganizationImpl {
	
	@Autowired
	RestTemplate restTemplate;
	
	@Autowired
	UriHelperNotApi uriHelperN;

	private HttpMethod hm;
	private URI uri;
	private final String COLLECTION = "org";
	
	private HttpEntity getEntity(Object obj) throws JsonProcessingException{
		ObjectMapper mapper = new ObjectMapper();
		HttpHeaders HEADERS = new HttpHeaders();	
		HEADERS.setContentType(MediaType.APPLICATION_JSON);
		return new HttpEntity<>(mapper.writeValueAsString(obj),HEADERS);
	}
	
	public ResponseEntity<OrganizationList> getList(OrganizationListSearch search){
		ResponseEntity<OrganizationList> response = restTemplate.getForEntity(uriHelperN.getFltrUrl(search, COLLECTION), OrganizationList.class);

		return response;
	}
	
	public ResponseEntity<Organization> getOne(String orgId){
		ResponseEntity<Organization> response = restTemplate.getForEntity(uriHelperN.getGETUri(COLLECTION, orgId), Organization.class);

		return response;
	}
	
	public ResponseEntity<ResponseResult> post(Organization org){
		ResponseEntity<ResponseResult> response;
		try{
			restTemplate.exchange(uriHelperN.getPOSTUri(COLLECTION), HttpMethod.POST, getEntity(org), String.class);
			response = new ResponseEntity<>(HttpStatus.CREATED);
		} catch(Exception e) {
			response = new ResponseEntity<>(HttpStatus.BAD_REQUEST);
		}

		return response;
	}
	
	public ResponseEntity<ResponseResult> put(Organization org){
		ResponseEntity<ResponseResult> response;
		Organization orgOld = this.getOne(org.getId()).getBody();
		if(!org.equals(orgOld)){
			try{
				restTemplate.exchange(uriHelperN.getPUTUri(COLLECTION, org.getId()), HttpMethod.PUT, getEntity(org), String.class);
				response = new ResponseEntity<>(HttpStatus.OK);
			} catch(Exception e) {
				response = new ResponseEntity<>(HttpStatus.BAD_REQUEST);
			}
		} else {
			response = new ResponseEntity<>(HttpStatus.NOT_MODIFIED);
		}

		return response;
	}
	
	public HttpStatus delete(String orgId){
		hm = HttpMethod.DELETE;
		
		ResponseEntity<String> response = restTemplate.exchange(uriHelperN.getGETUri(COLLECTION, orgId), hm, null, String.class);
		return response.getStatusCode();
	}
}

src/main/java/ais/demo/models/organization/OrganizationList.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ais.demo.models.organization;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Patskevich.S
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrganizationList {
	
	private final List<Organization> documents;
	private String companyName;
	private int count;
	private int c;
	
	public Map getOrgList(){
		Map<String, String> list = new HashMap <>();
		list.put("", "");
		documents.forEach((org) -> {
			list.put(org.getId(), org.getCompanyName());
		});
		
		return list;
	}
	
	public OrganizationList() {
        documents = new ArrayList<>();
    }

	public List<Organization> getDocuments() {
		return documents;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public int getCount() {
		return count;
	}
	
	public int getC() {
		return documents.size();
	}
	
	@Override
    public String toString() {
        return "Organizations{" +
                "documents=" + documents +
				"count=" + count +
				", c=" + c +
                '}';
    }
}

src/main/java/ais/demo/models/organization/OrganizationListSearch.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ais.demo.models.organization;

import ais.demo.helpers.Search;
import org.springframework.data.mongodb.core.query.Query;

/**
 *
 * @author Patskevich.S
 */
public class OrganizationListSearch implements Search{
	private int page;
	private int aP = 10;

	private Query query;
	
	@Override
	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	@Override
	public int getaP() {
		return aP;
	}

	public void setaP(int aP) {
		this.aP = aP;
	}	

	@Override
	public Query getQuery() {
		
		query = new Query();		
		return query;
	}
}

src/main/java/ais/demo/controller/OrganizationController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ais.demo.controller;

import ais.demo.helpers.PopUpHelper;
import ais.demo.models.organization.Organization;
import ais.demo.models.organization.OrganizationImpl;
import ais.demo.models.organization.OrganizationListSearch;
//import ais.demo.service.AuthenticationFacade;
import java.io.IOException;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import static org.springframework.util.StringUtils.isEmpty;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author Patskevich.S
 */
@Controller
@RequestMapping("/org")
public class OrganizationController {

	private int responseCode;
	private final String modalId = "orgModal";

//	@Autowired
//	private AuthenticationFacade auth;

	@Autowired
	private OrganizationImpl orgImpl;

	@Autowired
	private PopUpHelper popUp;

	@RequestMapping(value = "/index", method = RequestMethod.GET)
    public String actionIndex(Model model) throws IOException{

		OrganizationListSearch search = new OrganizationListSearch();

		model.addAttribute("list", orgImpl.getList(search).getBody());
		model.addAttribute("search", search);
//		model.addAttribute("role", auth.getRole());
//		model.addAttribute("login", auth.getLogin());

        return "organization/index";
    }

	@RequestMapping(value = "/indexRefresh", method = RequestMethod.POST)
    public String actionIndexRefresh(
				@ModelAttribute("search")OrganizationListSearch search,
				Model model){

		model.addAttribute("list", orgImpl.getList(search).getBody());
		model.addAttribute("page", search.getPage());
        model.addAttribute("startNumb", (search.getPage() - 1)  * 10);

        return "organization/_index";
    }

	@RequestMapping(value = "/view", method = RequestMethod.GET)
    public String actionView(Model model) {

//		Organization org = orgImpl.getOne(auth.getOrgId()).getBody();

//        model.addAttribute("org", org);
//		model.addAttribute("role", auth.getRole());
//		model.addAttribute("login", auth.getLogin());
		model.addAttribute("modalId", modalId);

        return "organization/view";
    }

	@RequestMapping(value = "/create", method = RequestMethod.POST)
    public String actionCreate(Model model) throws IOException{

        Organization org = new Organization();
		Map<Integer, String> directionList = org.getDistrictCodeList();

        model.addAttribute("org", org);
		model.addAttribute("directionList", directionList);
		model.addAttribute("title", "Создать запись об организации");
		model.addAttribute("modalId", modalId);

        return "organization/_form";
    }

    @RequestMapping(value = "/update", method = RequestMethod.POST)
    public String actionUpdate(@RequestParam(value = "id", required = true) String id, Model model) {

		Organization org = orgImpl.getOne(id).getBody();

        Map<Integer, String> directionList = org.getDistrictCodeList();

        model.addAttribute("org", org);
		model.addAttribute("directionList", directionList);
		model.addAttribute("title", "Редактировать запись об организации");
		model.addAttribute("modalId", modalId);

        return "organization/_form";
    }

	@RequestMapping(value = "/save", method = RequestMethod.POST)
    public String actionSave(@ModelAttribute("org") Organization org, Model model) {

		String method = "";
		if(!isEmpty(org.getId())){
			method = "PUT";
			responseCode = orgImpl.put(org).getStatusCodeValue();
		} else {
			method = "POST";
			responseCode = orgImpl.post(org).getStatusCodeValue();
		}


		System.out.println("responseCode " + responseCode);
		model.addAttribute("modalId", modalId);
		model = popUp.popUpModel(model, responseCode, "", "Organization", method);

        return "popUp/popUp";
    }

	@RequestMapping(value = "/delete", method = RequestMethod.POST)
    public String actionDelete(@RequestParam(value = "id", required = true) String id, Model model) {

		responseCode = orgImpl.delete(id).value();
		model.addAttribute("modalId", modalId);
        model = popUp.popUpModel(model, responseCode, "", "Organization", "DELETE");

        return "popUp/popUp";
    }
}

src/main/webapp/WEB-INF/view/organization/_form.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<div class="modal fade" uId="${modalId}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" uId="result">
            <div class="modal-header">
                <h5 class="modal-title" uId="exampleModalLongTitle">
                    ${title}                    
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form:form uId="org" modelAttribute="org">
                    <form:hidden path="uId" cssClass="uId" />
                    <div class="form-group">
                       <label for="companyName" class="col-form-label font-weight-bold">Наименование организации</label>
                       <form:input path="companyName" cssClass="form-control" uId="companyName"/>
                     </div>
                    <div class="form-group">
                        <label for="UNP" class="col-form-label font-weight-bold">УНП</label>
                        <form:input path="UNP" cssClass="form-control" uId="companyName"/>
                    </div>
                    <div class="form-group">                        
                        <label for="districtCode" class="col-form-label font-weight-bold">Область</label>
                        <form:select path="districtCode" uId='districtCode' cssClass="form-control" items="${directionList}"/>
                    </div>
                    <div class="form-group">
                       <label for="м" class="col-form-label font-weight-bold">Район</label>
                       <form:input path="district" cssClass="form-control" uId="district"/>
                    </div>
                    <div class="form-group">
                       <label for="city" class="col-form-label font-weight-bold">Город</label>
                       <form:input path="city" cssClass="form-control" uId="city"/>
                    </div>
                </form:form>               
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-success j-save" >Сохранить</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>                    
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/view/organization/_index.jsp
<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<table class="table table-striped table-hover table-sm">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование</th>
            <th scope="col">УНП</th>
            <th scope="col">Область</th>
            <th scope="col">Район</th>
            <th scope="col">Город</th>  
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <c:set var="count" value="0"/>
        <c:forEach var="item" items="${list.documents}">
            <tr>
                <th scope="row"><c:set var="count" value="${count + 1}"/>${count}</th>
                <td>${item.companyName}</td>
                <td>${item.UNP}</td>
                <td>${item.districtCodeName}</td>
                <td>${item.district}</td>
                <td>${item.city}</td>
                <td><button type="button" class="btn btn-primary j-update" data-uId="${item.uId}" data-toggle="tooltip" title="Редактировать"><i class="glyphicon glyphicon-edit"></i></button></td>
                <td><button type="button" class="btn btn-info j-view" data-uId="${item.uId}" data-toggle="tooltip" title="Просмотр"><i class="glyphicon glyphicon-eye-open"></i></button></td>
                <td><button type="button" class="btn btn-danger j-delete" data-uId="${item.uId}" data-toggle="tooltip" title="Удалить" data-toggle="modal" data-target="#confirm-delete"><i class="glyphicon glyphicon-remove"></i></button></td>
            </tr>
        </c:forEach>
    </tbody>
</table>
<div>
    <strong>Всего: </strong> ${list.count}
</div>
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link text-dark j-prev" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Пердыдущая</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link text-dark" uId="pageNumb" data-page="${page}">${page}</a></li>
        <li class="page-item">
            <a class="page-link text-dark <c:if test="${list.c == 10}">j-next</c:if>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Следующая</span>
            </a>
        </li>
    </ul>
</nav>

src/main/webapp/WEB-INF/view/organization/index.jsp
<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<t:index title="Организации">
    <jsp:attribute name="head">
        <script src="${pageContext.request.contextPath}/resources/js/organization.js"></script>
    </jsp:attribute>
        
     <jsp:attribute name="filter">
         <form:form uId="searchForm" modelAttribute="search">
            <div class="border border-light p-3">
                <form:hidden path="page" cssClass="page j-page" value="1"/>
            </div>
        </form:form>
        <button type="button" class="btn btn-primary j-create mb-4">Добавить организацию</button>  
    </jsp:attribute>
        
    <jsp:attribute name="body">
        <div class="modal fade" uId="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        Удалить организацию
                    </div>
                    <div class="modal-body">
                        Вы действительно хотите удалить организацию из списка?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button type="button" class="btn btn-success btn-ok" data-uId>Да</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="j-table">
            <table class="table table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Наименование</th>
                        <th scope="col">УНП</th>
                        <th scope="col">Область</th>
                        <th scope="col">Район</th>
                        <th scope="col">Город</th>  
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <c:set var="count" value="0"/>
                    <c:forEach var="item" items="${list.documents}">
                        
                        <tr>
                            <th scope="row"><c:set var="count" value="${count + 1}"/>${count}</th>
                            <td>${item.companyName}</td>
                            <td>${item.UNP}</td>
                            <td>${item.districtCodeName}</td>
                            <td>${item.district}</td>
                            <td>${item.city}</td>
                            <td><button type="button" class="btn btn-primary j-update" data-uId="${item.uId}" data-toggle="tooltip" title="Редактировать"><i class="glyphicon glyphicon-edit"></i></button></td>
                <td><button type="button" class="btn btn-info j-view" data-uId="${item.uId}" data-toggle="tooltip" title="Просмотр"><i class="glyphicon glyphicon-eye-open"></i></button></td>
                <td><button type="button" class="btn btn-danger j-delete" data-uId="${item.uId}" data-toggle="tooltip" title="Удалить" data-toggle="modal" data-target="#confirm-delete"><i class="glyphicon glyphicon-remove"></i></button></td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
            <div>
                <strong>Всего: </strong> ${list.count}
            </div>
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                        <a class="page-link text-dark" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item"><a class="page-link text-dark" uId="pageNumb" data-page="1">1</a></li>
                    <li class="page-item">
                        <a class="page-link text-dark <c:if test="${list.c == 10}">j-next</c:if>" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </jsp:attribute>    
</t:index>

                    

src/main/webapp/WEB-INF/view/organization/view.jsp
<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>

<t:index title="${org.companyName}" organization="active" role="${role}" login="${login}">
    <jsp:attribute name="head">
        <script src="${pageContext.request.contextPath}/resources/js/users.js"></script>
    </jsp:attribute>
     
    <jsp:attribute name="body">
        <div class="row border-bottom">        
            <div class="block">
                <table class="table table-borderless table-striped table-vcenter table-sm">
                    <tbody>
                        <tr><th>Наименование</th><td>${org.companyName}</td></tr>
                        <tr><th>УНП</th><td>${org.UNP}</td></tr>
                        <tr><th>Область</th><td>${org.districtCodeName}</td></tr>
                        <tr><th>Район</th><td>${org.district}</td></tr>
                        <tr><th>Город</th><td>${org.city}</td></tr>
                    </tbody>
                </table>			                    
            </div>  
        </div>
    </jsp:attribute> 
</t:index>